openapi: 3.0.4
info:
  title: Exporter log models
  description: Log models for logging services of exporter
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
paths: {}

components:
  schemas:
    CommonLogModel:
      title: Общая модель лога
      description: Общая модель лога для всех микросервисов системы
      type: object
      properties:
        messageTime:
          type: string
        logId:
          type: string
        source:
          type: string
        ad:
          $ref: '#/components/schemas/TemplateLogModel'
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ErrorLogModel'

    TemplateLogModel:
      title: Модель лога для микросервиса Exporter
      type: object
      properties:
        requestId:
          type: string
        operation:
          type: string
          enum:
            - create
            - read
            - update
            - delete
            - search
        requestTemplate:
          $ref: '#/components/schemas/TemplateLog'
        requestFilter:
          $ref: '#/components/schemas/TemplateFilterLog'
        responseTemplate:
          $ref: '#/components/schemas/TemplateLog'
        responseTemplates:
          type: array
          items:
            $ref: '#/components/schemas/TemplateLog'

    ErrorLogModel:
      title: Модель лога для ошибки
      type: object
      properties:
        message:
          type: string
        field:
          type: string
        code:
          type: string
        level:
          type: string

    TemplateLog:
      title: Модель лога для шаблона
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        visibility:
          type: string
        ownerId:
          type: string
        permissionsClient:
          type: array
          uniqueItems: true
          items:
            type: string

    TemplateFilterLog:
      title: Модель лога фильтра
      properties:
        searchString:
          type: string
        ownerId:
          type: string